# Generated by Django 4.1.2 on 2023-06-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accesorio',
            fields=[
                ('id_accesorio', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_accesorio', models.CharField(max_length=20)),
                ('precio_accesorio', models.CharField(max_length=10000000)),
            ],
        ),
        migrations.CreateModel(
            name='herramientaEl',
            fields=[
                ('id_herraEl', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_herraEl', models.CharField(max_length=20)),
                ('precio_herraEl', models.CharField(max_length=10000000)),
            ],
        ),
        migrations.CreateModel(
            name='herramientaIn',
            fields=[
                ('id_herraIn', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_herraIn', models.CharField(max_length=20)),
                ('precio_herraIn', models.CharField(max_length=10000000)),
            ],
        ),
    ]
